import React from "react";
import Footer from "/components/Footer";
import Header from "/components/Header";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function StudentGuide() {
  return (
    <div>
      <Head>
        <title>pocketclass</title>
        <meta
          name="terms and conditions"
          content="Generated by create next app"
        />
        <link rel="icon" href="/pc_favicon.ico" />
      </Head>
      {/* header */}
      <Header />

      {/*body*/}
      <main className="max-w-7xl mx-auto px-1 py-8 sm:px-5">
        <section>
          <h1 className="text-4xl font-semibold py-5">Our Student Guide</h1>
          <h1 className="text-xl font-semibold mt-5">
            We're excited to help you start your search for activities!
          </h1>
          <p className="text-md text-gray-700 mt-5">
            Benefits of using PocketClass:
          </p>
          <ul className="list-disc text-md ml-5 text-gray-700">
            <li>
              Filter your search activities and instructors that align with your
              preferences
            </li>
            <li>Read and leave reviews</li>
            <li>Secure Payments</li>
            <li>Refund policy for instructor cancellations</li>
          </ul>
          <p className="text-md text-gray-700 mt-5">
            Search for instructors using our comprehensive filters. Can’t find
            the activity you’re looking for? Complete this{" "}
            <a
              className="text-logo-red"
              target="_blank"
              href="https://gm81lvnyohz.typeform.com/to/IoLpsf9g"
            >
              form
            </a>
            , and our team will do our best to find you a match within 3-5
            business days!
          </p>
          <p className="text-md text-gray-700 mt-5">
            Have any other questions?{" "}
            <a
              className="text-logo-red"
              target="_blank"
              href="mailto: contact.pocketclass@gmail.com"
            >
              Send us an email
            </a>{" "}
            and our team will get back to you within 24 hours.
          </p>
        </section>
      </main>
      <Footer />
    </div>
  );
}
